#!/usr/bin/env python

import os
import sys

import scons_compiledb

from SCons.Script import *
from SCons.Script.SConscript import SConsEnvironment

env:SConsEnvironment = SConscript("include/godot-cpp/SConstruct")

# scons_compiledb.enable(env)
# env.CompileDb()

platform:str = env["platform"]
target:str = env["target"]
suffix:str = env["suffix"]
shlib_suffix:str = env["SHLIBSUFFIX"]

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
# env.Append(CPPPATH=["src/"])

sources = env.Glob("scr/*.cpp") + env.Glob("include/flecs/*.c")

env.Append(CPPPATH=["src/"])
env.Append(CPPPATH=["include/flecs/"])

if env["platform"] == "macos":
    library = env.SharedLibrary(
        f"../bin/libglecs.{platform}.{target}.framework/libgdexample.{platform}.{target}",
        source=sources,
    )
else:
    library = env.SharedLibrary(
        f"../bin/libglecs{suffix}{shlib_suffix}",
        source=sources,
    )

env.Default(library)

